packages:
  - packages/presets/*
  - packages/plugins/*
  - packages/adapters/*
  - apps/site
  - apps/web
  - examples/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - esbuild
  - sqlite3
  - unrs-resolver
