packages:
  - '!packages/kernel'
  - '!packages/server'
  - '!packages/runtime'
  - packages/presets/*
  - packages/plugins/*
  - apps/site
  - examples/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - esbuild
  - sqlite3
  - unrs-resolver
