name: ✨ Feature Request
description: Suggest a new feature for ObjectOS
title: '[Feature]: '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: input
    id: package
    attributes:
      label: Target Package
      description: Which package(s) would this feature affect?
      placeholder: e.g., @objectos/workflow, apps/web, new package
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is it related to a frustration?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: How large is this feature?
      options:
        - Small (single package, < 1 day)
        - Medium (multiple packages, 1-3 days)
        - Large (cross-cutting, > 3 days)
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or references.
